# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='Userpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(blank=True, default='')),
                ('post_photo', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
        migrations.AddField(
            model_name='userdetail',
            name='post',
            field=models.ManyToManyField(to='Insta.Userpost'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
