# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=120)),
                ('course_name', models.ManyToManyField(to='school3.Course22')),
            ],
        ),
    ]
