# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-16 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=120)),
                ('w_meaning', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='WordName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_name', models.CharField(max_length=120)),
            ],
        ),
    ]
