# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-15 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Word_Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_meaning', models.CharField(max_length=120)),
                ('word_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CacheApp.Word')),
            ],
        ),
    ]
