# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-15 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CacheApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word_meaning',
            name='word_name',
        ),
        migrations.AddField(
            model_name='word',
            name='word_meaning',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_name',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.DeleteModel(
            name='Word_Meaning',
        ),
    ]
