# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-15 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CacheApp', '0003_auto_20180215_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_name',
            field=models.CharField(max_length=120),
        ),
    ]
