# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-15 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CacheApp', '0005_auto_20180215_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordmeaning',
            old_name='word_meaning',
            new_name='word_meaning2',
        ),
        migrations.RenameField(
            model_name='wordmeaning',
            old_name='word_name',
            new_name='word_name2',
        ),
    ]
