# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-16 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CacheApp', '0006_auto_20180215_2343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordMeaning',
            new_name='Mean',
        ),
    ]
