# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-16 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CacheApp', '0007_auto_20180216_0001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mean',
        ),
    ]
