# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-16 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CacheApp', '0009_findmeaning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Findmeaning',
        ),
        migrations.AddField(
            model_name='word',
            name='word_meaning',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
